version: '2'
services:
  frontend:
    image: hello-ecs-frontend
    ports:
     - "5000:5000"
    links:
      - backend
    environment:
      - BACKEND_URL=http://backend:5000

  backend:
    image: hello-ecs-backend
#    environment:
#      - MOTD=Some cool stuff!
